version: '3.8'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=dynamodb,apigateway,lambda,rds,ssm,s3,cloudformation,iam,events,cloudwatch
      - DEBUG=1
      - DATA_DIR=/tmp/localstack_data 
    volumes:
      - localstack_data:/tmp/localstack_data  
      - /var/run/docker.sock:/var/run/docker.sock 
volumes:
  localstack_data:
